# Generated by Django 5.1.1 on 2024-09-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country_area',
            field=models.CharField(blank=True, help_text='Northern America', max_length=128, verbose_name='Country Area'),
        ),
    ]
