# Generated by Django 5.1.1 on 2024-09-29 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Location Name')),
                ('address_line', models.CharField(max_length=256, verbose_name='Street Address 1')),
                ('postal_code', models.CharField(max_length=32, verbose_name='Postal Code')),
                ('city', models.CharField(help_text='Ex: Los Angeles', max_length=64, verbose_name='City')),
                ('city_area', models.CharField(help_text='Ex: California', max_length=64, verbose_name='City Area')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='world.country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Warehouse Name')),
                ('main', models.BooleanField(default=False, verbose_name='Main')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Capacity')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='inventory.location', verbose_name='Location')),
            ],
        ),
    ]
